### ISSUE TITLE
B code inspection broken

### ISSUE THREAD

**Issue by mauke** [p5pclub/ref-util#10]
`B::Concise` doesn't work on code using `Ref::Util`:

```
$ perl -MRef::Util=is_arrayref -MO=Concise -e 'is_arrayref($foo)'
5  <@> leave[1 ref] vKP/REFC ->(end)
1     <0> enter ->2
2     <;> nextstate(main 1 -e:1) v:{ ->3
4     <0> is_arrayref_xop vK/1 ->5
Can't locate object method "first" via package "B::OP" at /home/mauke/usr/lib/perl5/5.22.1/i686-linux/B/Concise.pm line 470.
CHECK failed--call queue aborted.
```

Nor does `B::Deparse`:

```
$ perl -MRef::Util=is_arrayref -MO=Deparse -e 'is_arrayref($foo)'
Can't locate object method "first" via package "B::OP" at /home/mauke/usr/lib/perl5/5.22.1/B/Deparse.pm line 413.
CHECK failed--call queue aborted.
```

**Comment by xsawyerx** [comment]
@vickenty, any thoughts on this?

I think we talked about the [nullification](https://github.com/p5pclub/ref-util/blob/master/Util.xs#L59) of further ops be removed. Do you think it's related?

**Comment by vickenty** [comment]
It doesn't seem related. The problem is caused by `B` thinking `is_arrayref_xop` is nullary op (`<0>` in the output and the fact it is represented as `B::OP`). Maybe we need to set `xop_class` when calling `Perl_custom_op_register` too.

**Comment by arc** [comment]
@xsawyerx: I'm looking at this at the moment.

**Comment by xsawyerx** [comment]
FTR, the nullification is required.

**Comment by arc** [comment]
@xsawyerx yeah, seems so. This fix should be ready to merge.
