### ISSUE TITLE
why is the version on CPAN and in git different?

### ISSUE THREAD

**Issue by wchristian** [p5pclub/ref-util#18]
https://github.com/p5pclub/ref-util/blob/master/lib/Ref/Util.pm#L9

vs

https://metacpan.org/source/XSAWYERX/Ref-Util-0.020/lib/Ref/Util.pm#L9

**Comment by xsawyerx** [comment]
I'm missing something.

The first: '0.020'.
The second: '0.020'.

I've been staring at these numbers for a while and I'm not seeing it.
(No, really. I'm not joking. I've been staring for a while.)

**Comment by arc** [comment]
That's… odd — when I looked at this issue a few hours ago, the Github copy had a lower version number (0.011, iirc)

**Comment by xsawyerx** [comment]
Maybe some stuff I pushed before checking the issue. @wchristian, May I close this?

**Comment by wchristian** [comment]
@xsawyerx Yeah, we're in synch now. When i pulled earlier this was the commit i saw:

https://github.com/p5pclub/ref-util/commit/bdf1f2e401b6105b772a3230371a593dd686c7c2
