### ISSUE TITLE
possible patch required for  OpLASTSIB_set 

### ISSUE THREAD

**Issue by wchristian** [p5pclub/ref-util#20]
According to @mauke the following fallback implementation of OpLASTSIB_set is more correct:

```
#define OpLASTSIB_set(o, parent) ((o)->op_moresib = 0, (o)->op_sibling = NULL)
```

@arc : Do you see any problems with this? Asking since you commited the original fallback.

**Comment by ilmari** [comment]
Devel::PPPort 3.33 includes the `OpSIBLING` macro family, so you can just regenerate `ppport.h` instead of having your own versions of those macros.
