### ISSUE TITLE
reference and benchmark against Data::Util

### ISSUE THREAD

**Issue by y** [p5pclub/ref-util#27]
[Data::Util](https://metacpan.org/pod/Data::Util) contains similar functionality and has existed for a long time. It should probably be referenced in the SEE ALSO section and added to the benchmarks. It's also used by a bunch of other modules on CPAN: https://metacpan.org/requires/distribution/Data-Util?sort=[[2,1]]

**Comment by xsawyerx** [comment]
I agree.

**Comment by xsawyerx** [comment]
Latest release includes a speed comparison with `Data::Util`:
https://metacpan.org/pod/Ref::Util#SEE-ALSO

I thought about it and I honestly don't feel like curating every possible solution. As far as I can tell, this is the only one that:

1. Only looks at the container type. Nothing more.
2. Optionally (when supported) does it with custom ops.

**Comment by xsawyerx** [comment]
Latest release includes a speed comparison with `Data::Util`:
https://metacpan.org/pod/Ref::Util#SEE-ALSO

I thought about it and I honestly don't feel like curating every possible solution. As far as I can tell, this is the only one that:
1. Only looks at the container type. Nothing more.
2. Optionally (when supported) does it with custom ops.
