### ISSUE TITLE
Breaks with deep Readonly data structures [rt.cpan.org #110437]

### ISSUE THREAD

**Issue by xsawyerx** [p5pclub/ref-util#3]
Migrated from [rt.cpan.org#110437](https://rt.cpan.org/Ticket/Display.html?id=110437) (status was 'new')

Requestors:
- kaoru@slackwise.net

From kaoru@slackwise.net on 2015-12-18 17:09:45:

```
Test example:

------------------------------------

use 5.18.0;
use warnings;

use Test::More;

use Ref::Util 'is_hashref';
use Readonly;

# Read/write
{
    my $rh1 = { a => 1 };
    is ref($rh1), 'HASH', 'RW rh1 - old-school ref-eq';
    ok is_hashref($rh1),  'RW rh1 - new-school Ref::Util::is_hashref';

    my $rh2 = { a => { b => 2 } };
    is ref($rh2), 'HASH', 'RW rh2 - old-school ref-eq';
    ok is_hashref($rh2),  'RW rh2 - old-school Ref::Util::is_hashref';
    is ref($rh2->{a}), 'HASH', 'RW rh2->{a} - old-school ref-eq';
    ok is_hashref($rh2->{a}),  'RW rh2->{a} - old-school Ref::Util::is_hashref';
}

note "-" x 50;

# Readonly
{
    Readonly::Scalar my $rh1 => { a => 1 };
    is ref($rh1), 'HASH', 'RW rh1 - old-school ref-eq';
    ok is_hashref($rh1),  'RW rh1 - new-school Ref::Util::is_hashref';

    Readonly::Scalar my $rh2 => { a => { b => 2 } };
    is ref($rh2), 'HASH', 'RW rh2 - old-school ref-eq';
    ok is_hashref($rh2),  'RW rh2 - old-school Ref::Util::is_hashref';
    is ref($rh2->{a}), 'HASH', 'RW rh2->{a} - old-school ref-eq';
    ok is_hashref($rh2->{a}),  'RW rh2->{a} - old-school Ref::Util::is_hashref';
}

done_testing();

------------------------------------

alex@七番:~$ prove -v ref_util_readonly.t
ref_util_readonly.t .. 
ok 1 - RW rh1 - old-school ref-eq
ok 2 - RW rh1 - new-school Ref::Util::is_hashref
ok 3 - RW rh2 - old-school ref-eq
ok 4 - RW rh2 - old-school Ref::Util::is_hashref
ok 5 - RW rh2->{a} - old-school ref-eq
ok 6 - RW rh2->{a} - old-school Ref::Util::is_hashref
# --------------------------------------------------
ok 7 - RW rh1 - old-school ref-eq
ok 8 - RW rh1 - new-school Ref::Util::is_hashref
ok 9 - RW rh2 - old-school ref-eq
ok 10 - RW rh2 - old-school Ref::Util::is_hashref
ok 11 - RW rh2->{a} - old-school ref-eq
not ok 12 - RW rh2->{a} - old-school Ref::Util::is_hashref
1..12

#   Failed test 'RW rh2->{a} - old-school Ref::Util::is_hashref'
#   at ref_util_readonly.t line 34.
# Looks like you failed 1 test of 12.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/12 subtests 

Test Summary Report
-------------------
ref_util_readonly.t (Wstat: 256 Tests: 12 Failed: 1)
  Failed test:  12
  Non-zero exit status: 1
Files=1, Tests=12,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.02 cusr  0.00 csys =  0.06 CPU)
Result: FAIL

------------------------------------

```

**Comment by kaoru** [comment]
I'm also kaoru on Github if you need to @-message me for follow up questions :-)

**Comment by xsawyerx** [comment]
@kaoru Thank you for the bug report. I'm looking into it!

Happy to have pre-boarding time. :)

**Comment by xsawyerx** [comment]
`Readonly` seems to be adding magic. This causes several side-effects and I would venture to consider it as problematic as operator overloading - at least the way `Readonly` does it.

Consider the following code:

```
# your preample
Readonly::Scalar my $rh2 => { a => { b => 2 } };
is ref($rh2), 'HASH', 'RW rh2 - old-school ref-eq';
ok is_hashref($rh2),  'RW rh2 - old-school Ref::Util::is_hashref';
is ref($rh2->{a}), 'HASH', 'RW rh2->{a} - old-school ref-eq';
ok is_hashref($rh2->{a}),  'RW rh2->{a} - old-school Ref::Util::is_hashref';

# should show a hashref { a => { b => 2 } } -- Works!
use DDP;
p $rh2;
# result:
# \ {
#     a   {
#         b   2
#     } (tied to Readonly::Hash)
# } (tied to Readonly::Hash)

# should show a hashref { b => 2 } -- Works!
my $rh2_a = $rh2->{a};
p $rh2_a;
# result:
# \ {
#     b   2
# } (tied to Readonly::Hash)

# technically the same as above -- Fails!
p $rh2->{a};
# result:
# "HASH(0x187dcc8)"
```

The magic is triggers when it's fetched and then printed, but it's not triggered when it's used directly without being fetched. Silly magic.

I'm inclined to document this (magic being possibly problematic, depending how it's implemented, i suppose) and `Readonly` directly as _wtf crazy magic_ and then close the issue.

@kaoru, What do you think?

**Comment by plicease** [comment]
I replaced `Readonly` with `Const::Fast` and the test passed.  For what it is worth I am inclined to agree, that this is either a needs documentation and/or an issue with `Readonly`.

**Comment by xsawyerx** [comment]
`Const::Fast` just sets another flag on the SVs, while `Readonly` turns adds magic and hides stuff behind it, it seems.

We can make the functions check for magic and run it too, but that would have to be a different interface, and I'm not sure it's very useful.

```
use Ref::Util ':magic', qw<is_arrayref is_hashref>;
# or maybe...
use Ref::Util;
my $utils = Ref::Util->new( magic => 1 );
$utils->is_arrayref($foo);
# or maybe...
is_arrayref( $foo, magic => 1 );
# or maybe...
is_arrayref_with_magic($foo);
```

Or maybe just saying "if it's crazy magic, you're on your own", which is what I'm leaning towards.

We can definitely identify these situations and throw warnings or something.

**Comment by plicease** [comment]
My point on `Const::Fast` is that there is an alternative (maybe? I must confess to not really using either) for users that run into this, possibly worth referencing in any documentation on why `Readonly` this doesn't work.

**Comment by kaoru** [comment]
Great investigation and discussion guys, thanks!

@xsawyerx happy for you to close this. Maybe add a note to the POD about interaction with tied variables in general? It's not clear whether this means that tied variables in general don't play nicely with Ref::Util or if Readonly::XS is a special case because it does extra magic on top of tie'ing.

@plicease thanks for the recommendation on Const::Fast! I'll make sure I have tests for how I'm using Readonly::XS and then see if dropping in Const::Fast instead works just as well.

**Comment by xsawyerx** [comment]
@kaoru I'll play with some tied variables a bit and we'll see if it's a tied variable problem or the way `Readonly` does it.

Thank you for the replies. I only now saw them.

**Comment by xsawyerx** [comment]
Okay, conclusions:

If a tied variable is not a reference (but just a regular variable with magic), Ref::Util will not recognize it. I don't wish to change it because it will make `is_hashref` be meaningless because it isn't a hashref.

Instead, I opened #7 to inspect the idea of being able to examine if something is magical or not. This does not solve a situation where the question is "Can I use this as a...?" (which should be answered by a combination of 1. variable type, 2. magic, 3. overloading), which Ref::Util should probably not try and answer.

I think we reached a conclusion in this topic and thus I'm closing the issue.

@kaoru Thank you! :)

**Comment by kaoru** [comment]
@xsawyerx nice! Happy to help :-) The Nestoria code base is old enough and ugly enough that it makes a good test case for this kind of thing ;-)

**Comment by xsawyerx** [comment]
@kaoru I'm happy to inform that the next version of `Ref::Util` (0.100) will support `Readonly` variables. :)

**Comment by kaoru** [comment]
That's amazing! Great work man :grinning: I watched your [YAPC::NA/TPC](https://www.youtube.com/watch?v=gv-DCM9I8v0) presentation on Ref::Util too, it was awesome, nice work!

**Comment by xsawyerx** [comment]
Except I got almost everything wrong in the op code implementation. Thanks to Zefram, the op codes have been rewritten. :)

**Comment by xsawyerx** [comment]
By the way, the support for ties is thanks to Tony Cook (@tonycoz), not me. :)

**Comment by kaoru** [comment]
zefram++ tonycoz++ :+1: Ref::Util is a great idea, not surprised to see more Perl hackers jumping on it and getting it all shiny.
