### ISSUE TITLE
Undeclared dependency in v0.100

### ISSUE THREAD

**Issue by GeJ** [p5pclub/ref-util#30]
The addition of t/magic-readonly.t in the latest release introduces an undeclared dependency against the Readonly module. Sadly I've been spoiled with the latest auto-packagers framework lately, and I'm not sure where to put it in a raw Makefile. I would have loved to submit a proper PR for this. Sorry.

**Comment by xsawyerx** [comment]
Rats! I will have this fixed first thing tomorrow morning.

**Comment by xsawyerx** [comment]
0.101 with a fix has been released. Thank you! :)
