### ISSUE TITLE
Add a SYNOPSIS section to the doc

### ISSUE THREAD

**Issue by neilb** [p5pclub/ref-util#33]
I'm really used to seeing a SYNOPSIS section at the head of documentation on CPAN.

Would you be open to a pull request adding a brief SYNOPSIS, right after the NAME section?

It doesn't need to cover all functions, just enough to show the general idea.

Cheers,
Neil

**Comment by xsawyerx** [comment]
Of course!

**Comment by arc** [comment]
@neilb There's now a brief synopsis, visible at https://metacpan.org/pod/release/ARC/Ref-Util-0.202/lib/Ref/Util.pm — feel free to supply a PR and/or reopen this issue if you'd like it to be extended.
