### ISSUE TITLE
Document that Perl 5.010 is required, or support earlier versions

### ISSUE THREAD

**Issue by neilb** [p5pclub/ref-util#34]
Looking at [the CPAN Testers matrix](http://matrix.cpantesters.org/?dist=Ref-Util), it's clear that Ref::Util requires 5.010 or later, even though the [metadata](https://metacpan.org/source/XSAWYERX/Ref-Util-0.101/META.json#L37) says 5.6.2 is required.

As a start, it would be good if it were documented that as a minimum 5.10 is required, but even better would be to support earlier versions of Perl, even if that required a fallback to a pure-perl implementation.

Cheers,
Neil

**Comment by arc** [comment]
Thanks, @neilb.

@xsawyerx it looks to me like the master branch already has changes to restore building under 5.8 (and I think 5.6 too, if I'm reading it right). I'm willing to cut a release, but I don't have enough permissions in Pause to do an authorized release. If you're willing to grant me co-maint, I'll happily do a release in the next day or so.

**Comment by xsawyerx** [comment]
I was delayed with this because I wanted to first split it to XS and PP, but I think it's better if we just cut this out before it gets worse and I'll get back to working on the split afterwards.

Cleaned up a bit. Updated stuff.

Now rerunning benchmarks (since there was some optimization provided in this release) and will cut a release after. Regardless I'll add @arc to comaint today because duh.

**Comment by neilb** [comment]
Thanks!

That latest release now appears to support 5.8.6+

Here's a [fail report on 5.8.5](http://www.cpantesters.org/cpan/report/8a396096-cdee-11e6-b1f4-a92f14f04b7f), for example.

**Comment by xsawyerx** [comment]
This doesn't seem to be a fail in the code, just in a function from `B::Concise` used to inspect what was created in a test. I'll patch that up and release a new version.

**Comment by neilb** [comment]
@xsawyerx :+1:

**Comment by xsawyerx** [comment]
Version 1.111 released, which adds this fix. Thank you. :)
