### ISSUE TITLE
Makefile issue (0.200)

### ISSUE THREAD

**Issue by eserte** [p5pclub/ref-util#39]
The current release does not build on my freebsd & linux machines, see http://fast-matrix.cpantesters.org/?dist=Ref-Util;reports=1#sl=0,1

On the freebsd machines the build log looks like this:
```
Output from '/usr/bin/make':

"Makefile", line 693: Need an operator
make: fatal errors encountered -- cannot continue
```

On the linux machines (debian & centos) it's a different error message:
```
Output from '/usr/bin/make':

Makefile:693: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
```

**Comment by eserte** [comment]
May easily be reproduced if an older version of Ref::Util (e.g. 0.113) is installed.

**Comment by karenetheridge** [comment]
fixed in git. will poke someone to release soon.

**Comment by arc** [comment]
Thanks, released https://metacpan.org/release/ARC/Ref-Util-0.201
