### ISSUE TITLE
Something is broken under -MO=Deparse

### ISSUE THREAD

**Issue by burak** [p5pclub/ref-util#42]
$  perl -MO=Deparse -e 'use Ref::Util qw(is_scalarref); die 42 if is_scalarref \$_'
unexpected OP_CUSTOM (is_scalarref) at /Users/bgursoy/.plenv/versions/5.26.0/lib/perl5/5.26.0/B/Deparse.pm line 1667.
use Ref::Util ('is_scalarref');
die 42 if XXX;
-e syntax OK

Earlier perls also complain about "unexpected OP_IS_SCALARREF", but that looks like some internal changes while error being the same.

**Comment by xsawyerx** [comment]
This was just resolved by Ref::Util::XS 0.117, released just now.
